"""Identifier generation for Crowdin's string `identifier` column.

Two-phase identifier lifecycle:

  1. Temporary identifier (`tmp:YYMMDD:HHMMSS:mmm:<sha1[:8]>`)
     - Generated by register_new_strings.py for canonical TSV rows that have
       no identifier yet (brand new rows added in xlsx).
     - Written to the canonical TSV's `identifier` column and committed.
     - Pushed to Crowdin on the next push_source — Crowdin assigns the
       string's numeric_id at registration but the `identifier` field stays
       as the tmp: string we sent.

  2. Permanent identifier (`str(numeric_id)`, e.g. "428", "652")
     - fetch_crowdin_ids.py scans Crowdin for `tmp:` prefixed identifiers,
       PATCHes each to `str(numeric_id)`, then writes the numeric_id back
       to the canonical TSV's `identifier` column. From this point on the
       row's identifier is stable across all push/pull operations.

The timestamp in the temp_id makes it:
  - Sortable / human-traceable ("which date was this row added?")
  - Filterable in Crowdin UI ("show me strings still pending PATCH")
  - Unique enough to survive rapid additions (millisecond granularity)

The temp_id MUST be persisted to canonical TSV BEFORE any push attempt — if
register_new_strings.py is skipped and push fires the fallback path, every
retry generates a fresh timestamp and risks creating duplicate Crowdin
strings on transient failures.

Legacy:
  make_translation_id / make_texture_id (below) generate content-based
  composite identifiers and were the canonical identifier scheme prior to
  the numeric_id migration (2026-06-03). Retained for back-compat with
  archived snapshots and migration scripts; no production code path uses
  them.
"""
import hashlib
import time
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Hash + temp_id primitives
# ---------------------------------------------------------------------------

# How many hex chars to keep from sha1 — collision risk @ 8 chars is
# ~1 in 4 billion, plenty for our scale (~3000 rows).
HASH_LENGTH = 8


def short_hash(s: str) -> str:
    """Stable, short hex sha1 of a string."""
    return hashlib.sha1(s.encode("utf-8")).hexdigest()[:HASH_LENGTH]


def _timestamp_parts() -> str:
    """Return 'YYMMDD:HHMMSS:mmm' for the current UTC time.

    UTC (not local) so timestamps generated on different developers' machines
    sort consistently in Crowdin and look the same in git diffs.
    """
    now = datetime.now(timezone.utc)
    return now.strftime("%y%m%d:%H%M%S") + f":{now.microsecond // 1000:03d}"


def temp_id_for_translation(row: dict) -> str:
    """Generate a temporary identifier for a Translation row.

    Format: `tmp:YYMMDD:HHMMSS:mmm:<sha1(text|filename|name)[:8]>`

    Returns "" for rows that must not be pushed (ignore / untranslatable /
    empty text). Caller filters on empty return.
    """
    if (row.get("method") or "").strip() == "ignore":
        return ""
    if (row.get("untranslatable") or "").strip() == "1":
        return ""
    text = (row.get("text") or "").strip()
    if not text:
        return ""
    seed = "|".join([
        text,
        (row.get("filename") or "").strip(),
        (row.get("name") or "").strip(),
    ])
    return f"tmp:{_timestamp_parts()}:{short_hash(seed)}"


def temp_id_for_texture(row: dict) -> str:
    """Generate a temporary identifier for a Texture row.

    Format: `tmp:YYMMDD:HHMMSS:mmm:<sha1(Text|File Name)[:8]>`

    Returns "" for rows that must not be pushed (ignore / pending / empty
    text). Caller filters on empty return.
    """
    if (row.get("method") or "").strip().lower() in ("ignore", "pending"):
        return ""
    text = (row.get("Text") or "").strip()
    if not text:
        return ""
    seed = "|".join([text, (row.get("File Name") or "").strip()])
    return f"tmp:{_timestamp_parts()}:{short_hash(seed)}"


def is_temporary_identifier(identifier: str) -> bool:
    """True if the identifier still uses the `tmp:` bootstrap format."""
    return identifier.startswith("tmp:")


# ---------------------------------------------------------------------------
# Legacy: content-based composite identifiers (pre-2026-06-03 scheme).
# Retained for archived snapshots and one-off migration scripts only.
# ---------------------------------------------------------------------------

def _is_global_translation(row: dict) -> bool:
    """A Translation row is 'global' if it uses substr, or it's
    literal/pattern WITHOUT a location."""
    method = (row.get("method") or "").strip()
    if method == "substr":
        return True
    if method in ("literal", "pattern", ""):
        location = (row.get("location") or "").strip()
        return not location
    return False


def make_translation_id(row: dict) -> str:
    """Legacy composite identifier for a Translation row.

    Format: `T:<filename>:<parent>:<name>:<type>:<property>:<unique_id>:<sha1(text)[:8]>`
    or     `T:GLOBAL:<method>:<sha1(text)[:8]>` for global rows.
    """
    method = (row.get("method") or "").strip()
    if method == "ignore":
        return ""
    if (row.get("untranslatable") or "").strip() == "1":
        return ""
    if not (row.get("text") or "").strip():
        return ""

    if _is_global_translation(row):
        effective_method = method or "literal"
        return f"T:GLOBAL:{effective_method}:{short_hash(row['text'])}"

    parts = [
        (row.get("filename") or "").strip(),
        (row.get("parent") or "").strip(),
        (row.get("name") or "").strip(),
        (row.get("type") or "").strip(),
        (row.get("property") or "").strip(),
        (row.get("unique_id") or "").strip(),
        short_hash(row.get("text", "")),
    ]
    return "T:" + ":".join(parts)


def make_texture_id(row: dict) -> str:
    """Legacy composite identifier for a Texture row.

    Format: `X:<File_Name>:<sha1(Text)[:8]>`
    """
    text = (row.get("Text") or "").strip()
    if not text:
        return ""
    file_name = (row.get("File Name") or "").strip()
    parts = [file_name or "_", short_hash(text)]
    return "X:" + ":".join(parts)
