"""Maintainer wrapper: pull Crowdin translations → canonical TSV.

Combines two steps:
  1. crowdin download                          Crowdin → Crowdin_Mirror/translations/
  2. crowdin/apply_to_repo.py                  Crowdin_Mirror → Translations/<locale>/<cat>/*.tsv

Run this periodically (e.g. weekly) to bring the repo's canonical TSVs in
sync with the latest translations on Crowdin. After running, review the
diff and commit:

    git diff Translations/
    git add Translations/
    git commit -m "Pull translations from Crowdin"

xlsx files are NOT regenerated by this command — run `rebuild_xlsx.py
<locale>` separately if you want updated xlsx for review.

Required setup:
  - Crowdin CLI installed: https://crowdin.github.io/crowdin-cli/installation
  - API token env var:     setx CROWDIN_PERSONAL_TOKEN "<your-token>"

Usage:
    python tools/pull_from_crowdin.py              # all locales
    python tools/pull_from_crowdin.py Korean       # one locale
    python tools/pull_from_crowdin.py --skip-download   # skip Crowdin server step (apply only)
"""
import argparse
import subprocess
import sys
from pathlib import Path

LOCALE_TO_CROWDIN_ID = {
    "Korean": "ko",
    "French": "fr",
    "Portuguese_BR": "pt-BR",
}


def run(cmd: list, cwd: Path) -> bool:
    print(f"\n>>> {' '.join(str(c) for c in cmd)}")
    result = subprocess.run(cmd, cwd=cwd)
    return result.returncode == 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "locale",
        nargs="?",
        default=None,
        help=f"Optional locale to limit. Supported: {', '.join(LOCALE_TO_CROWDIN_ID)}. "
             f"If omitted, applies to all locales.",
    )
    parser.add_argument(
        "--skip-download",
        action="store_true",
        help="Skip Crowdin server download (use existing Crowdin_Mirror state)",
    )
    args = parser.parse_args()

    if args.locale is not None and args.locale not in LOCALE_TO_CROWDIN_ID:
        print(f"[ERROR] Unknown locale: {args.locale}", file=sys.stderr)
        print(f"        Supported: {', '.join(LOCALE_TO_CROWDIN_ID)}", file=sys.stderr)
        return 1

    tools_dir = Path(__file__).resolve().parent
    repo_root = tools_dir.parent

    # 1. crowdin download (Crowdin → Crowdin_Mirror)
    if not args.skip_download:
        download_cmd = ["crowdin", "download"]
        if args.locale is not None:
            download_cmd += ["-l", LOCALE_TO_CROWDIN_ID[args.locale]]
        if not run(download_cmd, cwd=repo_root):
            print("\n[ERROR] Crowdin download failed", file=sys.stderr)
            print("        Check Crowdin CLI install + CROWDIN_PERSONAL_TOKEN env var", file=sys.stderr)
            return 1

    # 2. apply Crowdin_Mirror → canonical TSV
    apply_cmd = [sys.executable, "crowdin/apply_to_repo.py"]
    if args.locale is not None:
        apply_cmd.append(args.locale)
    if not run(apply_cmd, cwd=tools_dir):
        print("\n[ERROR] apply_to_repo step failed", file=sys.stderr)
        return 1

    target = args.locale if args.locale else "all locales"
    print(f"\n[OK] Pulled Crowdin translations to canonical TSVs ({target})")
    print("Next: review, then commit:")
    print("  git diff Translations/")
    print("  git add Translations/")
    print('  git commit -m "Pull translations from Crowdin"')
    print()
    print("(Optional) regenerate xlsx for review:")
    if args.locale:
        print(f"  python tools/rebuild_xlsx.py {args.locale}")
    else:
        for loc in LOCALE_TO_CROWDIN_ID:
            print(f"  python tools/rebuild_xlsx.py {loc}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
