"""Maintainer wrapper: pull Crowdin translations -> canonical TSV (Python-only, no CLI).

Combines two steps:
  1. Crowdin SDK build + download         Crowdin -> Crowdin_Mirror/translations/<locale>/
  2. crowdin/apply_to_repo.py             Crowdin_Mirror -> Translations/<locale>/<cat>/*.tsv

Run this periodically (e.g. weekly) to bring the repo's canonical TSVs in
sync with the latest translations on Crowdin. After running, review the
diff and commit:

    git diff Translations/
    git add Translations/
    git commit -m "Pull translations from Crowdin"

xlsx files are NOT regenerated by this command -- run `rebuild_xlsx.py
<locale>` separately if you want updated xlsx for review.

Required setup (one-time):
  - Python deps: pip install -r tools/requirements.txt   (includes crowdin-api-client)
  - Crowdin token: copy secrets.example.json to secrets.json (repo root)
                   and fill in `crowdin_personal_token`.

No Crowdin CLI / Java install required.

Usage:
    python tools/pull_from_crowdin.py Korean              # one locale
    python tools/pull_from_crowdin.py all                 # all locales (explicit keyword)
    python tools/pull_from_crowdin.py Korean --skip-download
    python tools/pull_from_crowdin.py all --skip-download

Note: `all` is required to pull every locale at once. Bare invocation without
a positional arg errors out -- guard against accidentally running a long
all-locales build unintentionally.
"""
import argparse
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from utils.locale_config import load_crowdin_locale_map


def run(cmd: list, cwd: Path) -> bool:
    print(f"\n>>> {' '.join(str(c) for c in cmd)}")
    result = subprocess.run(cmd, cwd=cwd)
    return result.returncode == 0


def main() -> int:
    locale_map = load_crowdin_locale_map()

    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "locale",
        help=f"Locale folder name (one of: {', '.join(locale_map)}) "
             f"OR the keyword `all` to pull every locale. "
             f"Required -- bare invocation is rejected to prevent accidental mass pull.",
    )
    parser.add_argument(
        "--skip-download",
        action="store_true",
        help="Skip Crowdin server download (use existing Crowdin_Mirror state)",
    )
    args = parser.parse_args()

    pull_all = args.locale.strip().lower() == "all"
    if not pull_all and args.locale not in locale_map:
        print(f"[ERROR] Unknown locale: {args.locale}", file=sys.stderr)
        print(f"        Supported: {', '.join(locale_map)} OR `all`", file=sys.stderr)
        print(f"        (active locale in Trans To Vostok/locale.json AND crowdin_id present in tools/languages.json)",
              file=sys.stderr)
        return 1

    try:
        from crowdin.api_client import download_translations
    except ImportError as e:
        print(f"\n[ERROR] Could not import Crowdin SDK helper: {e}", file=sys.stderr)
        print("        Run: pip install -r tools/requirements.txt", file=sys.stderr)
        return 1

    tools_dir = Path(__file__).resolve().parent
    repo_root = tools_dir.parent

    # 1. Crowdin -> Crowdin_Mirror via SDK build + download
    if not args.skip_download:
        language_id = None if pull_all else locale_map[args.locale]
        try:
            download_translations(language_id=language_id, extract_to=repo_root)
        except Exception as e:
            print(f"\n[ERROR] Crowdin download failed: {e}", file=sys.stderr)
            print("        Check secrets.json:crowdin_personal_token", file=sys.stderr)
            return 1

    # 2. apply Crowdin_Mirror -> canonical TSV
    apply_cmd = [sys.executable, "crowdin/apply_to_repo.py"]
    if not pull_all:
        apply_cmd.append(args.locale)
    if not run(apply_cmd, cwd=tools_dir):
        print("\n[ERROR] apply_to_repo step failed", file=sys.stderr)
        return 1

    target = "all locales" if pull_all else args.locale
    print(f"\n[OK] Pulled Crowdin translations to canonical TSVs ({target})")
    print(f"     (commit Translations/ to share + refresh push diff baseline)")
    print("Next: review, then commit:")
    print("  git diff Translations/")
    print("  git add Translations/")
    print('  git commit -m "Pull translations from Crowdin"')
    print()
    print("(Optional) regenerate xlsx for review:")
    if pull_all:
        for loc in locale_map:
            print(f"  python tools/rebuild_xlsx.py {loc}")
    else:
        print(f"  python tools/rebuild_xlsx.py {args.locale}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
